"""baseline schema

Revision ID: 20260310_01
Revises: 
Create Date: 2026-03-10 17:31:46.294546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20260310_01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentaccesstoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('token_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('token_hint', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_digest', name='uq_agent_access_token_digest')
    )
    op.create_index(op.f('ix_agentaccesstoken_created_at'), 'agentaccesstoken', ['created_at'], unique=False)
    op.create_index(op.f('ix_agentaccesstoken_expires_at'), 'agentaccesstoken', ['expires_at'], unique=False)
    op.create_index(op.f('ix_agentaccesstoken_last_used_at'), 'agentaccesstoken', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_agentaccesstoken_revoked_at'), 'agentaccesstoken', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_agentaccesstoken_token_digest'), 'agentaccesstoken', ['token_digest'], unique=False)
    op.create_index(op.f('ix_agentaccesstoken_updated_at'), 'agentaccesstoken', ['updated_at'], unique=False)
    op.create_index(op.f('ix_agentaccesstoken_user_id'), 'agentaccesstoken', ['user_id'], unique=False)
    op.create_table('agentidempotencykey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('response_json', sqlmodel.sql.sqltypes.AutoString(length=16000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope', 'idempotency_key', name='uq_agent_idempotency_user_scope_key')
    )
    op.create_index(op.f('ix_agentidempotencykey_created_at'), 'agentidempotencykey', ['created_at'], unique=False)
    op.create_index(op.f('ix_agentidempotencykey_scope'), 'agentidempotencykey', ['scope'], unique=False)
    op.create_index(op.f('ix_agentidempotencykey_updated_at'), 'agentidempotencykey', ['updated_at'], unique=False)
    op.create_index(op.f('ix_agentidempotencykey_user_id'), 'agentidempotencykey', ['user_id'], unique=False)
    op.create_table('agenttask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('input_json', sqlmodel.sql.sqltypes.AutoString(length=16000), nullable=False),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(length=16000), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenttask_completed_at'), 'agenttask', ['completed_at'], unique=False)
    op.create_index(op.f('ix_agenttask_created_at'), 'agenttask', ['created_at'], unique=False)
    op.create_index(op.f('ix_agenttask_status'), 'agenttask', ['status'], unique=False)
    op.create_index(op.f('ix_agenttask_task_type'), 'agenttask', ['task_type'], unique=False)
    op.create_index(op.f('ix_agenttask_updated_at'), 'agenttask', ['updated_at'], unique=False)
    op.create_index(op.f('ix_agenttask_user_id'), 'agenttask', ['user_id'], unique=False)
    op.create_table('assetmutationaudit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('agent_task_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('before_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assetmutationaudit_actor_user_id'), 'assetmutationaudit', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_assetmutationaudit_agent_task_id'), 'assetmutationaudit', ['agent_task_id'], unique=False)
    op.create_index(op.f('ix_assetmutationaudit_created_at'), 'assetmutationaudit', ['created_at'], unique=False)
    op.create_index(op.f('ix_assetmutationaudit_entity_id'), 'assetmutationaudit', ['entity_id'], unique=False)
    op.create_index(op.f('ix_assetmutationaudit_entity_type'), 'assetmutationaudit', ['entity_type'], unique=False)
    op.create_index(op.f('ix_assetmutationaudit_operation'), 'assetmutationaudit', ['operation'], unique=False)
    op.create_index(op.f('ix_assetmutationaudit_user_id'), 'assetmutationaudit', ['user_id'], unique=False)
    op.create_table('cashaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashaccount_user_id'), 'cashaccount', ['user_id'], unique=False)
    op.create_table('cashledgerentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('happened_on', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('holding_transaction_id', sa.Integer(), nullable=True),
    sa.Column('cash_transfer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashledgerentry_cash_account_id'), 'cashledgerentry', ['cash_account_id'], unique=False)
    op.create_index(op.f('ix_cashledgerentry_cash_transfer_id'), 'cashledgerentry', ['cash_transfer_id'], unique=False)
    op.create_index(op.f('ix_cashledgerentry_created_at'), 'cashledgerentry', ['created_at'], unique=False)
    op.create_index(op.f('ix_cashledgerentry_entry_type'), 'cashledgerentry', ['entry_type'], unique=False)
    op.create_index(op.f('ix_cashledgerentry_happened_on'), 'cashledgerentry', ['happened_on'], unique=False)
    op.create_index(op.f('ix_cashledgerentry_holding_transaction_id'), 'cashledgerentry', ['holding_transaction_id'], unique=False)
    op.create_index(op.f('ix_cashledgerentry_user_id'), 'cashledgerentry', ['user_id'], unique=False)
    op.create_table('cashtransfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('source_amount', sa.Float(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('source_currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('target_currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('transferred_on', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashtransfer_created_at'), 'cashtransfer', ['created_at'], unique=False)
    op.create_index(op.f('ix_cashtransfer_from_account_id'), 'cashtransfer', ['from_account_id'], unique=False)
    op.create_index(op.f('ix_cashtransfer_to_account_id'), 'cashtransfer', ['to_account_id'], unique=False)
    op.create_index(op.f('ix_cashtransfer_transferred_on'), 'cashtransfer', ['transferred_on'], unique=False)
    op.create_index(op.f('ix_cashtransfer_user_id'), 'cashtransfer', ['user_id'], unique=False)
    op.create_table('dashboardcorrection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('series_scope', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('granularity', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('bucket_utc', sa.DateTime(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('corrected_value', sa.Float(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboardcorrection_bucket_utc'), 'dashboardcorrection', ['bucket_utc'], unique=False)
    op.create_index(op.f('ix_dashboardcorrection_created_at'), 'dashboardcorrection', ['created_at'], unique=False)
    op.create_index(op.f('ix_dashboardcorrection_granularity'), 'dashboardcorrection', ['granularity'], unique=False)
    op.create_index(op.f('ix_dashboardcorrection_series_scope'), 'dashboardcorrection', ['series_scope'], unique=False)
    op.create_index(op.f('ix_dashboardcorrection_symbol'), 'dashboardcorrection', ['symbol'], unique=False)
    op.create_index(op.f('ix_dashboardcorrection_user_id'), 'dashboardcorrection', ['user_id'], unique=False)
    op.create_table('fixedasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('current_value_cny', sa.Float(), nullable=False),
    sa.Column('purchase_value_cny', sa.Float(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixedasset_user_id'), 'fixedasset', ['user_id'], unique=False)
    op.create_table('holdinghistorysyncrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('trigger_symbol', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdinghistorysyncrequest_completed_at'), 'holdinghistorysyncrequest', ['completed_at'], unique=False)
    op.create_index(op.f('ix_holdinghistorysyncrequest_requested_at'), 'holdinghistorysyncrequest', ['requested_at'], unique=False)
    op.create_index(op.f('ix_holdinghistorysyncrequest_started_at'), 'holdinghistorysyncrequest', ['started_at'], unique=False)
    op.create_index(op.f('ix_holdinghistorysyncrequest_status'), 'holdinghistorysyncrequest', ['status'], unique=False)
    op.create_index(op.f('ix_holdinghistorysyncrequest_user_id'), 'holdinghistorysyncrequest', ['user_id'], unique=False)
    op.create_table('holdingperformancesnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdingperformancesnapshot_created_at'), 'holdingperformancesnapshot', ['created_at'], unique=False)
    op.create_index(op.f('ix_holdingperformancesnapshot_scope'), 'holdingperformancesnapshot', ['scope'], unique=False)
    op.create_index(op.f('ix_holdingperformancesnapshot_symbol'), 'holdingperformancesnapshot', ['symbol'], unique=False)
    op.create_index(op.f('ix_holdingperformancesnapshot_user_id'), 'holdingperformancesnapshot', ['user_id'], unique=False)
    op.create_table('holdingtransactioncashsettlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('holding_transaction_id', sa.Integer(), nullable=False),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('handling', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('settled_amount', sa.Float(), nullable=False),
    sa.Column('settled_currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('source_amount', sa.Float(), nullable=False),
    sa.Column('source_currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('flow_direction', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('auto_created_cash_account', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holding_transaction_id', name='uq_holding_transaction_cash_settlement_transaction')
    )
    op.create_index(op.f('ix_holdingtransactioncashsettlement_cash_account_id'), 'holdingtransactioncashsettlement', ['cash_account_id'], unique=False)
    op.create_index(op.f('ix_holdingtransactioncashsettlement_created_at'), 'holdingtransactioncashsettlement', ['created_at'], unique=False)
    op.create_index(op.f('ix_holdingtransactioncashsettlement_holding_transaction_id'), 'holdingtransactioncashsettlement', ['holding_transaction_id'], unique=False)
    op.create_index(op.f('ix_holdingtransactioncashsettlement_user_id'), 'holdingtransactioncashsettlement', ['user_id'], unique=False)
    op.create_table('inboxmessagevisibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('message_kind', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_kind', 'message_id', name='uq_inbox_message_visibility_user_kind_message')
    )
    op.create_index(op.f('ix_inboxmessagevisibility_hidden_at'), 'inboxmessagevisibility', ['hidden_at'], unique=False)
    op.create_index(op.f('ix_inboxmessagevisibility_message_id'), 'inboxmessagevisibility', ['message_id'], unique=False)
    op.create_index(op.f('ix_inboxmessagevisibility_message_kind'), 'inboxmessagevisibility', ['message_kind'], unique=False)
    op.create_index(op.f('ix_inboxmessagevisibility_user_id'), 'inboxmessagevisibility', ['user_id'], unique=False)
    op.create_table('liabilityentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liabilityentry_user_id'), 'liabilityentry', ['user_id'], unique=False)
    op.create_table('otherasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('current_value_cny', sa.Float(), nullable=False),
    sa.Column('original_value_cny', sa.Float(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otherasset_user_id'), 'otherasset', ['user_id'], unique=False)
    op.create_table('outboxjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(length=48), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(length=16000), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outboxjob_available_at'), 'outboxjob', ['available_at'], unique=False)
    op.create_index(op.f('ix_outboxjob_completed_at'), 'outboxjob', ['completed_at'], unique=False)
    op.create_index(op.f('ix_outboxjob_created_at'), 'outboxjob', ['created_at'], unique=False)
    op.create_index(op.f('ix_outboxjob_dedup_key'), 'outboxjob', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_outboxjob_job_type'), 'outboxjob', ['job_type'], unique=False)
    op.create_index(op.f('ix_outboxjob_started_at'), 'outboxjob', ['started_at'], unique=False)
    op.create_index(op.f('ix_outboxjob_status'), 'outboxjob', ['status'], unique=False)
    op.create_index(op.f('ix_outboxjob_updated_at'), 'outboxjob', ['updated_at'], unique=False)
    op.create_index(op.f('ix_outboxjob_user_id'), 'outboxjob', ['user_id'], unique=False)
    op.create_table('portfoliosnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('total_value_cny', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfoliosnapshot_created_at'), 'portfoliosnapshot', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfoliosnapshot_user_id'), 'portfoliosnapshot', ['user_id'], unique=False)
    op.create_table('releasenote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=6000), nullable=False),
    sa.Column('source_feedback_ids_json', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releasenote_created_at'), 'releasenote', ['created_at'], unique=False)
    op.create_index(op.f('ix_releasenote_created_by'), 'releasenote', ['created_by'], unique=False)
    op.create_index(op.f('ix_releasenote_published_at'), 'releasenote', ['published_at'], unique=False)
    op.create_index(op.f('ix_releasenote_version'), 'releasenote', ['version'], unique=False)
    op.create_table('releasenotedelivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releasenotedelivery_delivered_at'), 'releasenotedelivery', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_releasenotedelivery_release_note_id'), 'releasenotedelivery', ['release_note_id'], unique=False)
    op.create_index(op.f('ix_releasenotedelivery_seen_at'), 'releasenotedelivery', ['seen_at'], unique=False)
    op.create_index(op.f('ix_releasenotedelivery_user_id'), 'releasenotedelivery', ['user_id'], unique=False)
    op.create_table('securityholding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('fallback_currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('cost_basis_price', sa.Float(), nullable=True),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('broker', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securityholding_symbol'), 'securityholding', ['symbol'], unique=False)
    op.create_index(op.f('ix_securityholding_user_id'), 'securityholding', ['user_id'], unique=False)
    op.create_table('securityholdingtransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('fallback_currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('broker', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('traded_on', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securityholdingtransaction_created_at'), 'securityholdingtransaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_securityholdingtransaction_side'), 'securityholdingtransaction', ['side'], unique=False)
    op.create_index(op.f('ix_securityholdingtransaction_symbol'), 'securityholdingtransaction', ['symbol'], unique=False)
    op.create_index(op.f('ix_securityholdingtransaction_traded_on'), 'securityholdingtransaction', ['traded_on'], unique=False)
    op.create_index(op.f('ix_securityholdingtransaction_user_id'), 'securityholdingtransaction', ['user_id'], unique=False)
    op.create_table('useraccount',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('password_digest', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('email_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_useraccount_email'), 'useraccount', ['email'], unique=False)
    op.create_index(op.f('ix_useraccount_email_digest'), 'useraccount', ['email_digest'], unique=False)
    op.create_table('userfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('reply_message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('replied_by', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('reply_seen_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('assignee', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('ack_deadline', sa.DateTime(), nullable=True),
    sa.Column('internal_note', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=True),
    sa.Column('internal_note_updated_at', sa.DateTime(), nullable=True),
    sa.Column('internal_note_updated_by', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(length=96), nullable=True),
    sa.Column('dedupe_window_minutes', sa.Integer(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userfeedback_ack_deadline'), 'userfeedback', ['ack_deadline'], unique=False)
    op.create_index(op.f('ix_userfeedback_acknowledged_at'), 'userfeedback', ['acknowledged_at'], unique=False)
    op.create_index(op.f('ix_userfeedback_assignee'), 'userfeedback', ['assignee'], unique=False)
    op.create_index(op.f('ix_userfeedback_category'), 'userfeedback', ['category'], unique=False)
    op.create_index(op.f('ix_userfeedback_created_at'), 'userfeedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_userfeedback_fingerprint'), 'userfeedback', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_userfeedback_internal_note_updated_at'), 'userfeedback', ['internal_note_updated_at'], unique=False)
    op.create_index(op.f('ix_userfeedback_last_seen_at'), 'userfeedback', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_userfeedback_priority'), 'userfeedback', ['priority'], unique=False)
    op.create_index(op.f('ix_userfeedback_replied_at'), 'userfeedback', ['replied_at'], unique=False)
    op.create_index(op.f('ix_userfeedback_reply_seen_at'), 'userfeedback', ['reply_seen_at'], unique=False)
    op.create_index(op.f('ix_userfeedback_resolved_at'), 'userfeedback', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_userfeedback_source'), 'userfeedback', ['source'], unique=False)
    op.create_index(op.f('ix_userfeedback_status'), 'userfeedback', ['status'], unique=False)
    op.create_index(op.f('ix_userfeedback_user_id'), 'userfeedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userfeedback_user_id'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_status'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_source'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_resolved_at'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_reply_seen_at'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_replied_at'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_priority'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_last_seen_at'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_internal_note_updated_at'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_fingerprint'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_created_at'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_category'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_assignee'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_acknowledged_at'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_ack_deadline'), table_name='userfeedback')
    op.drop_table('userfeedback')
    op.drop_index(op.f('ix_useraccount_email_digest'), table_name='useraccount')
    op.drop_index(op.f('ix_useraccount_email'), table_name='useraccount')
    op.drop_table('useraccount')
    op.drop_index(op.f('ix_securityholdingtransaction_user_id'), table_name='securityholdingtransaction')
    op.drop_index(op.f('ix_securityholdingtransaction_traded_on'), table_name='securityholdingtransaction')
    op.drop_index(op.f('ix_securityholdingtransaction_symbol'), table_name='securityholdingtransaction')
    op.drop_index(op.f('ix_securityholdingtransaction_side'), table_name='securityholdingtransaction')
    op.drop_index(op.f('ix_securityholdingtransaction_created_at'), table_name='securityholdingtransaction')
    op.drop_table('securityholdingtransaction')
    op.drop_index(op.f('ix_securityholding_user_id'), table_name='securityholding')
    op.drop_index(op.f('ix_securityholding_symbol'), table_name='securityholding')
    op.drop_table('securityholding')
    op.drop_index(op.f('ix_releasenotedelivery_user_id'), table_name='releasenotedelivery')
    op.drop_index(op.f('ix_releasenotedelivery_seen_at'), table_name='releasenotedelivery')
    op.drop_index(op.f('ix_releasenotedelivery_release_note_id'), table_name='releasenotedelivery')
    op.drop_index(op.f('ix_releasenotedelivery_delivered_at'), table_name='releasenotedelivery')
    op.drop_table('releasenotedelivery')
    op.drop_index(op.f('ix_releasenote_version'), table_name='releasenote')
    op.drop_index(op.f('ix_releasenote_published_at'), table_name='releasenote')
    op.drop_index(op.f('ix_releasenote_created_by'), table_name='releasenote')
    op.drop_index(op.f('ix_releasenote_created_at'), table_name='releasenote')
    op.drop_table('releasenote')
    op.drop_index(op.f('ix_portfoliosnapshot_user_id'), table_name='portfoliosnapshot')
    op.drop_index(op.f('ix_portfoliosnapshot_created_at'), table_name='portfoliosnapshot')
    op.drop_table('portfoliosnapshot')
    op.drop_index(op.f('ix_outboxjob_user_id'), table_name='outboxjob')
    op.drop_index(op.f('ix_outboxjob_updated_at'), table_name='outboxjob')
    op.drop_index(op.f('ix_outboxjob_status'), table_name='outboxjob')
    op.drop_index(op.f('ix_outboxjob_started_at'), table_name='outboxjob')
    op.drop_index(op.f('ix_outboxjob_job_type'), table_name='outboxjob')
    op.drop_index(op.f('ix_outboxjob_dedup_key'), table_name='outboxjob')
    op.drop_index(op.f('ix_outboxjob_created_at'), table_name='outboxjob')
    op.drop_index(op.f('ix_outboxjob_completed_at'), table_name='outboxjob')
    op.drop_index(op.f('ix_outboxjob_available_at'), table_name='outboxjob')
    op.drop_table('outboxjob')
    op.drop_index(op.f('ix_otherasset_user_id'), table_name='otherasset')
    op.drop_table('otherasset')
    op.drop_index(op.f('ix_liabilityentry_user_id'), table_name='liabilityentry')
    op.drop_table('liabilityentry')
    op.drop_index(op.f('ix_inboxmessagevisibility_user_id'), table_name='inboxmessagevisibility')
    op.drop_index(op.f('ix_inboxmessagevisibility_message_kind'), table_name='inboxmessagevisibility')
    op.drop_index(op.f('ix_inboxmessagevisibility_message_id'), table_name='inboxmessagevisibility')
    op.drop_index(op.f('ix_inboxmessagevisibility_hidden_at'), table_name='inboxmessagevisibility')
    op.drop_table('inboxmessagevisibility')
    op.drop_index(op.f('ix_holdingtransactioncashsettlement_user_id'), table_name='holdingtransactioncashsettlement')
    op.drop_index(op.f('ix_holdingtransactioncashsettlement_holding_transaction_id'), table_name='holdingtransactioncashsettlement')
    op.drop_index(op.f('ix_holdingtransactioncashsettlement_created_at'), table_name='holdingtransactioncashsettlement')
    op.drop_index(op.f('ix_holdingtransactioncashsettlement_cash_account_id'), table_name='holdingtransactioncashsettlement')
    op.drop_table('holdingtransactioncashsettlement')
    op.drop_index(op.f('ix_holdingperformancesnapshot_user_id'), table_name='holdingperformancesnapshot')
    op.drop_index(op.f('ix_holdingperformancesnapshot_symbol'), table_name='holdingperformancesnapshot')
    op.drop_index(op.f('ix_holdingperformancesnapshot_scope'), table_name='holdingperformancesnapshot')
    op.drop_index(op.f('ix_holdingperformancesnapshot_created_at'), table_name='holdingperformancesnapshot')
    op.drop_table('holdingperformancesnapshot')
    op.drop_index(op.f('ix_holdinghistorysyncrequest_user_id'), table_name='holdinghistorysyncrequest')
    op.drop_index(op.f('ix_holdinghistorysyncrequest_status'), table_name='holdinghistorysyncrequest')
    op.drop_index(op.f('ix_holdinghistorysyncrequest_started_at'), table_name='holdinghistorysyncrequest')
    op.drop_index(op.f('ix_holdinghistorysyncrequest_requested_at'), table_name='holdinghistorysyncrequest')
    op.drop_index(op.f('ix_holdinghistorysyncrequest_completed_at'), table_name='holdinghistorysyncrequest')
    op.drop_table('holdinghistorysyncrequest')
    op.drop_index(op.f('ix_fixedasset_user_id'), table_name='fixedasset')
    op.drop_table('fixedasset')
    op.drop_index(op.f('ix_dashboardcorrection_user_id'), table_name='dashboardcorrection')
    op.drop_index(op.f('ix_dashboardcorrection_symbol'), table_name='dashboardcorrection')
    op.drop_index(op.f('ix_dashboardcorrection_series_scope'), table_name='dashboardcorrection')
    op.drop_index(op.f('ix_dashboardcorrection_granularity'), table_name='dashboardcorrection')
    op.drop_index(op.f('ix_dashboardcorrection_created_at'), table_name='dashboardcorrection')
    op.drop_index(op.f('ix_dashboardcorrection_bucket_utc'), table_name='dashboardcorrection')
    op.drop_table('dashboardcorrection')
    op.drop_index(op.f('ix_cashtransfer_user_id'), table_name='cashtransfer')
    op.drop_index(op.f('ix_cashtransfer_transferred_on'), table_name='cashtransfer')
    op.drop_index(op.f('ix_cashtransfer_to_account_id'), table_name='cashtransfer')
    op.drop_index(op.f('ix_cashtransfer_from_account_id'), table_name='cashtransfer')
    op.drop_index(op.f('ix_cashtransfer_created_at'), table_name='cashtransfer')
    op.drop_table('cashtransfer')
    op.drop_index(op.f('ix_cashledgerentry_user_id'), table_name='cashledgerentry')
    op.drop_index(op.f('ix_cashledgerentry_holding_transaction_id'), table_name='cashledgerentry')
    op.drop_index(op.f('ix_cashledgerentry_happened_on'), table_name='cashledgerentry')
    op.drop_index(op.f('ix_cashledgerentry_entry_type'), table_name='cashledgerentry')
    op.drop_index(op.f('ix_cashledgerentry_created_at'), table_name='cashledgerentry')
    op.drop_index(op.f('ix_cashledgerentry_cash_transfer_id'), table_name='cashledgerentry')
    op.drop_index(op.f('ix_cashledgerentry_cash_account_id'), table_name='cashledgerentry')
    op.drop_table('cashledgerentry')
    op.drop_index(op.f('ix_cashaccount_user_id'), table_name='cashaccount')
    op.drop_table('cashaccount')
    op.drop_index(op.f('ix_assetmutationaudit_user_id'), table_name='assetmutationaudit')
    op.drop_index(op.f('ix_assetmutationaudit_operation'), table_name='assetmutationaudit')
    op.drop_index(op.f('ix_assetmutationaudit_entity_type'), table_name='assetmutationaudit')
    op.drop_index(op.f('ix_assetmutationaudit_entity_id'), table_name='assetmutationaudit')
    op.drop_index(op.f('ix_assetmutationaudit_created_at'), table_name='assetmutationaudit')
    op.drop_index(op.f('ix_assetmutationaudit_agent_task_id'), table_name='assetmutationaudit')
    op.drop_index(op.f('ix_assetmutationaudit_actor_user_id'), table_name='assetmutationaudit')
    op.drop_table('assetmutationaudit')
    op.drop_index(op.f('ix_agenttask_user_id'), table_name='agenttask')
    op.drop_index(op.f('ix_agenttask_updated_at'), table_name='agenttask')
    op.drop_index(op.f('ix_agenttask_task_type'), table_name='agenttask')
    op.drop_index(op.f('ix_agenttask_status'), table_name='agenttask')
    op.drop_index(op.f('ix_agenttask_created_at'), table_name='agenttask')
    op.drop_index(op.f('ix_agenttask_completed_at'), table_name='agenttask')
    op.drop_table('agenttask')
    op.drop_index(op.f('ix_agentidempotencykey_user_id'), table_name='agentidempotencykey')
    op.drop_index(op.f('ix_agentidempotencykey_updated_at'), table_name='agentidempotencykey')
    op.drop_index(op.f('ix_agentidempotencykey_scope'), table_name='agentidempotencykey')
    op.drop_index(op.f('ix_agentidempotencykey_created_at'), table_name='agentidempotencykey')
    op.drop_table('agentidempotencykey')
    op.drop_index(op.f('ix_agentaccesstoken_user_id'), table_name='agentaccesstoken')
    op.drop_index(op.f('ix_agentaccesstoken_updated_at'), table_name='agentaccesstoken')
    op.drop_index(op.f('ix_agentaccesstoken_token_digest'), table_name='agentaccesstoken')
    op.drop_index(op.f('ix_agentaccesstoken_revoked_at'), table_name='agentaccesstoken')
    op.drop_index(op.f('ix_agentaccesstoken_last_used_at'), table_name='agentaccesstoken')
    op.drop_index(op.f('ix_agentaccesstoken_expires_at'), table_name='agentaccesstoken')
    op.drop_index(op.f('ix_agentaccesstoken_created_at'), table_name='agentaccesstoken')
    op.drop_table('agentaccesstoken')
    # ### end Alembic commands ###
